spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
